import React from 'react'
import ComboBox from '../ComboBox/ComboBox'
const FlightSearchdata = [
  {
    iata: 'BPM',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Hyderabad',
    airportName: 'Hyderabad Begumpet Airport',
    country: 'India',
    countryCode: 'IN',
    group_type: 'NB',
  },
  {
    iata: 'IXX',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Bidar',
    airportName: 'Bidar Airport',
    distanceInfoText: '113 km from Hyderabad',
    country: 'India',
    countryCode: 'IN',
    group_type: 'NB',
  },
  {
    iata: 'KJB',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Kurnool',
    airportName: 'Kurnool Airport',
    distanceInfoText: '196 km from Hyderabad',
    country: 'India',
    countryCode: 'IN',
    group_type: 'NB',
  },

  {
    iata: 'HYG',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Hydaburg',
    airportName: 'SPB-AK',
    country: 'United States',
    countryCode: 'US',
    group_type: '',
  },
  {
    iata: 'VGA',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Vijayawada',
    airportName: 'Vijayawada Airport',
    country: 'India',
    countryCode: 'IN',
    group_type: '',
  },
  {
    iata: 'NDC',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Nanded',
    airportName: 'Shri Guru Gobind Singh Ji Airport',
    country: 'India',
    countryCode: 'IN',
    group_type: '',
  },
  {
    iata: 'HYA',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Hyannis',
    airportName: 'Barnstable-MA',
    country: 'United States',
    countryCode: 'US',
    group_type: '',
  },
  {
    iata: 'HYS',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Hays',
    airportName: 'Hays-KS',
    country: 'United States',
    countryCode: 'US',
    group_type: '',
  },
  {
    iata: 'HKT',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Phuket',
    airportName: 'Phuket',
    country: 'Thailand',
    countryCode: 'TH',
    group_type: '',
  },
  {
    iata: 'HER',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Heraklion',
    airportName: 'N. Kazantzakis Apt.',
    country: 'Greece',
    countryCode: 'GR',
    group_type: '',
  },
  {
    iata: 'HRG',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Hurghada',
    airportName: 'Hurghada',
    country: 'Egypt',
    countryCode: 'EG',
    group_type: '',
  },
  {
    iata: 'HUZ',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Huizhou',
    airportName: 'Huizhou',
    country: 'China',
    countryCode: 'CN',
    group_type: '',
  },
  {
    iata: 'HUX',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Huatulco',
    airportName: 'Huatulco',
    country: 'Mexico',
    countryCode: 'MX',
    group_type: '',
  },
  {
    iata: 'HTN',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Hotan',
    airportName: 'Hotan',
    country: 'China',
    countryCode: 'CN',
    group_type: '',
  },
  {
    iata: 'HLZ',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Hamilton',
    airportName: 'Hamilton',
    country: 'New Zealand',
    countryCode: 'NZ',
    group_type: '',
  },
  {
    iata: 'HYN',
    icon: 'https://imgak.mmtcdn.com/flights/assets/media/dt/common/icons/ic-flight-onward.png',
    Cityname: 'Huangyan',
    airportName: 'Huangyan',
    country: 'China',
    countryCode: 'CN',
    group_type: '',
  },
]
export default FlightSearchdata
